### ISSUE TITLE
issue starting

### ISSUE THREAD

**Issue by v0d0r** [timoa/app-stores-prometheus-exporter#7]
npm start results in the below error.
I suspect this is because of npm version that is too low.  Can you confirm if there is a version minimum requirement?  Current version: 3.10.10

> app-stores-prometheus-exporter@0.4.4 start /home/prometheus/app-stores-prometheus-exporter
> node src/exporter

/home/prometheus/app-stores-prometheus-exporter/src/exporter.js:11
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by timoa** [comment]
Hi @v0d0r!

Sorry for the delay :/

This issue is still valid?

Thanks for your help to improve the project :)
